// ── js/data.js ──
// Toutes les citations du site.
// Chaque citation a un `day` (0, 1, 2, …) qui détermine quel jour elle apparaît.
// `textEn` est la version originale en anglais (optionnelle).

const ALL_QUOTES = [
  // ── Jour 0 ──
  {
    id: 1,
    text: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.",
    textEn: "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    author: "Albert Einstein",
    era: "Physicien, 1879–1955",
    cat: "Sagesse",
    day: 0,
  },
  {
    id: 2,
    text: "Soyez le changement que vous voulez voir dans le monde.",
    textEn: "Be the change you wish to see in the world.",
    author: "Mahatma Gandhi",
    era: "Leader, 1869–1948",
    cat: "Inspiration",
    day: 0,
  },
  {
    id: 3,
    text: "Le secret d'un bon début, c'est de finir quelque chose.",
    author: "Mark Twain",
    era: "Écrivain, 1835–1910",
    cat: "Action",
    day: 0,
  },
  {
    id: 4,
    text: "L'imagination est plus importante que le savoir.",
    textEn: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    era: "Physicien, 1879–1955",
    cat: "Créativité",
    day: 0,
  },

  // ── Jour 1 ──
  {
    id: 5,
    text: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",
    textEn: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
    author: "Antoine de Saint-Exupéry",
    era: "Écrivain, 1900–1944",
    cat: "Sagesse",
    day: 1,
  },
  {
    id: 6,
    text: "Le courage n'est pas l'absence de peur, mais le jugement que quelque chose est plus important que la peur.",
    textEn: "Courage is not the absence of fear, but rather the judgment that something else is more important than fear.",
    author: "Ambrose Redmoon",
    era: "Écrivain, 1933–1996",
    cat: "Courage",
    day: 1,
  },
  {
    id: 7,
    text: "L'échec est simplement l'opportunité de recommencer, cette fois plus intelligemment.",
    textEn: "Failure is simply the opportunity to begin again, this time more intelligently.",
    author: "Henry Ford",
    era: "Industriel, 1863–1947",
    cat: "Résilience",
    day: 1,
  },
  {
    id: 8,
    text: "Mieux vaut allumer une chandelle que maudire l'obscurité.",
    textEn: "It is better to light a candle than to curse the darkness.",
    author: "Confucius",
    era: "Philosophe, 551–479 av. J.-C.",
    cat: "Sagesse",
    day: 1,
  },

  // ── Jour 2 ──
  {
    id: 9,
    text: "Il ne faut pas attendre d'être parfait pour commencer quelque chose de bien.",
    author: "Galilée",
    era: "Astronome, 1564–1642",
    cat: "Action",
    day: 2,
  },
  {
    id: 10,
    text: "L'art de vivre, c'est l'art de savoir croire aux miracles.",
    author: "Jacques Prévert",
    era: "Poète, 1900–1977",
    cat: "Philosophie",
    day: 2,
  },
  {
    id: 11,
    text: "Le génie, c'est un pour cent d'inspiration et quatre-vingt-dix-neuf pour cent de transpiration.",
    textEn: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    author: "Thomas Edison",
    era: "Inventeur, 1847–1931",
    cat: "Travail",
    day: 2,
  },
  {
    id: 12,
    text: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.",
    textEn: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.",
    author: "Sénèque",
    era: "Philosophe, 4 av. J.-C.–65 ap. J.-C.",
    cat: "Courage",
    day: 2,
  },

  // ── Jour 3 ──
  {
    id: 13,
    text: "La seule façon de faire du bon travail, c'est d'aimer ce que vous faites.",
    textEn: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    era: "Entrepreneur, 1955–2011",
    cat: "Travail",
    day: 3,
  },
  {
    id: 14,
    text: "Celui qui déplace des montagnes commence par enlever les petites pierres.",
    textEn: "The man who moves a mountain begins by carrying away small stones.",
    author: "Confucius",
    era: "Philosophe, 551–479 av. J.-C.",
    cat: "Persévérance",
    day: 3,
  },
  {
    id: 15,
    text: "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute.",
    textEn: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    author: "Nelson Mandela",
    era: "Leader, 1918–2013",
    cat: "Résilience",
    day: 3,
  },
  {
    id: 16,
    text: "Le bonheur n'est pas quelque chose de tout fait. Il vient de vos propres actions.",
    textEn: "Happiness is not something ready-made. It comes from your own actions.",
    author: "Dalaï Lama",
    era: "Leader spirituel, né en 1935",
    cat: "Bonheur",
    day: 3,
  },

  // ── Jour 4 ──
  {
    id: 17,
    text: "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre toujours.",
    textEn: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    author: "Mahatma Gandhi",
    era: "Leader, 1869–1948",
    cat: "Sagesse",
    day: 4,
  },
  {
    id: 18,
    text: "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.",
    textEn: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    era: "Première dame, 1884–1962",
    cat: "Inspiration",
    day: 4,
  },
  {
    id: 19,
    text: "Dans le milieu du chemin de notre vie, je me retrouvai dans une forêt obscure.",
    textEn: "In the middle of the journey of our life, I came to myself within a dark wood.",
    author: "Dante Alighieri",
    era: "Poète, 1265–1321",
    cat: "Philosophie",
    day: 4,
  },
  {
    id: 20,
    text: "Ce qui ne me tue pas me rend plus fort.",
    textEn: "That which does not kill me makes me stronger.",
    author: "Friedrich Nietzsche",
    era: "Philosophe, 1844–1900",
    cat: "Résilience",
    day: 4,
  },

  // ── Jour 5 ──
  {
    id: 21,
    text: "Tout ce que vous pouvez imaginer est réel.",
    textEn: "Everything you can imagine is real.",
    author: "Pablo Picasso",
    era: "Peintre, 1881–1973",
    cat: "Créativité",
    day: 5,
  },
  {
    id: 22,
    text: "La connaissance parle, mais la sagesse écoute.",
    textEn: "Knowledge speaks, but wisdom listens.",
    author: "Jimi Hendrix",
    era: "Musicien, 1942–1970",
    cat: "Sagesse",
    day: 5,
  },
  {
    id: 23,
    text: "Le voyage de mille lieues commence toujours par un premier pas.",
    textEn: "A journey of a thousand miles begins with a single step.",
    author: "Lao Tseu",
    era: "Philosophe, VIe siècle av. J.-C.",
    cat: "Action",
    day: 5,
  },
  {
    id: 24,
    text: "Soyez vous-même, tous les autres sont déjà pris.",
    textEn: "Be yourself; everyone else is already taken.",
    author: "Oscar Wilde",
    era: "Écrivain, 1854–1900",
    cat: "Identité",
    day: 5,
  },

  // ── Jour 6 ──
  {
    id: 25,
    text: "La vie n'est pas mesurée au nombre de respirations que nous prenons, mais aux moments qui nous coupent le souffle.",
    textEn: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    author: "Maya Angelou",
    era: "Poète, 1928–2014",
    cat: "Inspiration",
    day: 6,
  },
  {
    id: 26,
    text: "Je n'ai pas échoué. J'ai simplement trouvé dix mille façons qui ne fonctionnent pas.",
    textEn: "I have not failed. I've just found ten thousand ways that won't work.",
    author: "Thomas Edison",
    era: "Inventeur, 1847–1931",
    cat: "Persévérance",
    day: 6,
  },
  {
    id: 27,
    text: "Le monde est un livre, et ceux qui ne voyagent pas n'en lisent qu'une page.",
    textEn: "The world is a book, and those who do not travel read only one page.",
    author: "Saint Augustin",
    era: "Philosophe, 354–430",
    cat: "Sagesse",
    day: 6,
  },
  {
    id: 28,
    text: "La liberté, c'est la responsabilité. C'est pourquoi tout le monde la craint.",
    textEn: "Liberty means responsibility. That is why most men dread it.",
    author: "George Bernard Shaw",
    era: "Écrivain, 1856–1950",
    cat: "Philosophie",
    day: 6,
  },

  // ── Jour 7 ──
  {
    id: 29,
    text: "Ce que nous pensons, nous le devenons.",
    textEn: "What we think, we become.",
    author: "Bouddha",
    era: "Philosophe, Ve siècle av. J.-C.",
    cat: "Sagesse",
    day: 7,
  },
  {
    id: 30,
    text: "La créativité, c'est l'intelligence qui s'amuse.",
    textEn: "Creativity is intelligence having fun.",
    author: "Albert Einstein",
    era: "Physicien, 1879–1955",
    cat: "Créativité",
    day: 7,
  },
  {
    id: 31,
    text: "Il n'y a qu'une façon d'éviter la critique : ne rien faire, ne rien dire et n'être rien.",
    textEn: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
    author: "Aristote",
    era: "Philosophe, 384–322 av. J.-C.",
    cat: "Courage",
    day: 7,
  },
  {
    id: 32,
    text: "Le bonheur est disponible. S'il vous plaît, soyez heureux.",
    textEn: "Happiness is available. Please help yourself.",
    author: "Thich Nhat Hanh",
    era: "Moine bouddhiste, 1926–2022",
    cat: "Bonheur",
    day: 7,
  },

  // ── Jour 8 ──
  {
    id: 33,
    text: "Deux choses sont infinies : l'univers et la bêtise humaine. Et encore, pour l'univers, je n'en suis pas certain.",
    textEn: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
    author: "Albert Einstein",
    era: "Physicien, 1879–1955",
    cat: "Philosophie",
    day: 8,
  },
  {
    id: 34,
    text: "Nous sommes tous des génies. Mais si vous jugez un poisson sur sa capacité à grimper à un arbre, il passera sa vie à croire qu'il est stupide.",
    textEn: "Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.",
    author: "Albert Einstein",
    era: "Physicien, 1879–1955",
    cat: "Inspiration",
    day: 8,
  },
  {
    id: 35,
    text: "Le succès c'est d'aller d'échec en échec sans perdre son enthousiasme.",
    textEn: "Success is walking from failure to failure with no loss of enthusiasm.",
    author: "Winston Churchill",
    era: "Homme d'État, 1874–1965",
    cat: "Persévérance",
    day: 8,
  },
  {
    id: 36,
    text: "En période de changement, ceux qui apprennent héritent de la terre, tandis que ceux qui ont appris se retrouvent magnifiquement équipés pour un monde qui n'existe plus.",
    textEn: "In times of change, learners inherit the earth, while the learned find themselves beautifully equipped to deal with a world that no longer exists.",
    author: "Eric Hoffer",
    era: "Philosophe, 1902–1983",
    cat: "Sagesse",
    day: 8,
  },

  // ── Jour 9 ──
  {
    id: 37,
    text: "Si vous pensez que l'aventure est dangereuse, essayez la routine. Elle est mortelle.",
    textEn: "If you think adventure is dangerous, try routine; it is lethal.",
    author: "Paulo Coelho",
    era: "Écrivain, né en 1947",
    cat: "Action",
    day: 9,
  },
  {
    id: 38,
    text: "La seule limite à notre épanouissement de demain sera nos doutes d'aujourd'hui.",
    textEn: "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    era: "Président, 1882–1945",
    cat: "Inspiration",
    day: 9,
  },
  {
    id: 39,
    text: "Agissez comme si ce que vous faites faisait une différence. C'est le cas.",
    textEn: "Act as if what you do makes a difference. It does.",
    author: "William James",
    era: "Philosophe, 1842–1910",
    cat: "Action",
    day: 9,
  },
  {
    id: 40,
    text: "Vous ne pouvez pas revenir en arrière et changer le début, mais vous pouvez démarrer là où vous êtes et changer la fin.",
    textEn: "You can't go back and change the beginning, but you can start where you are and change the ending.",
    author: "C. S. Lewis",
    era: "Écrivain, 1898–1963",
    cat: "Résilience",
    day: 9,
  },

  // ── Jour 10 ──
  {
    id: 41,
    text: "La vie, c'est ce qui arrive quand vous êtes occupé à faire d'autres projets.",
    textEn: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    era: "Musicien, 1940–1980",
    cat: "Philosophie",
    day: 10,
  },
  {
    id: 42,
    text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    textEn: "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    author: "Mère Teresa",
    era: "Humanitaire, 1910–1997",
    cat: "Bonheur",
    day: 10,
  },
  {
    id: 43,
    text: "Le temps que vous avez passé pour votre rose fait votre rose si importante.",
    author: "Antoine de Saint-Exupéry",
    era: "Écrivain, 1900–1944",
    cat: "Sagesse",
    day: 10,
  },
  {
    id: 44,
    text: "Ce n'est pas la montagne que nous conquérons, mais nous-mêmes.",
    textEn: "It is not the mountain we conquer, but ourselves.",
    author: "Edmund Hillary",
    era: "Alpiniste, 1919–2008",
    cat: "Courage",
    day: 10,
  },

  // ── Jour 11 ──
  {
    id: 45,
    text: "L'amour ne consiste pas à se regarder l'un l'autre, mais à regarder ensemble dans la même direction.",
    textEn: "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
    author: "Antoine de Saint-Exupéry",
    era: "Écrivain, 1900–1944",
    cat: "Philosophie",
    day: 11,
  },
  {
    id: 46,
    text: "La nuit la plus sombre prendra fin et le soleil se lèvera.",
    textEn: "Even the darkest night will end and the sun will rise.",
    author: "Victor Hugo",
    era: "Écrivain, 1802–1885",
    cat: "Résilience",
    day: 11,
  },
  {
    id: 47,
    text: "Pour accomplir de grandes choses, nous devons non seulement agir, mais aussi rêver ; non seulement planifier, mais aussi croire.",
    textEn: "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.",
    author: "Anatole France",
    era: "Écrivain, 1844–1924",
    cat: "Inspiration",
    day: 11,
  },
  {
    id: 48,
    text: "La meilleure vengeance est une vie réussie.",
    textEn: "The best revenge is massive success.",
    author: "Frank Sinatra",
    era: "Artiste, 1915–1998",
    cat: "Action",
    day: 11,
  },

  // ── Jour 12 ──
  {
    id: 49,
    text: "Si vous ne pouvez pas voler, courez. Si vous ne pouvez pas courir, marchez. Si vous ne pouvez pas marcher, rampez. Mais quoi que vous fassiez, continuez d'avancer.",
    textEn: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
    author: "Martin Luther King Jr.",
    era: "Pasteur & militant, 1929–1968",
    cat: "Persévérance",
    day: 12,
  },
  {
    id: 50,
    text: "Un rêve que vous rêvez seul n'est qu'un rêve. Un rêve que vous rêvez ensemble est une réalité.",
    textEn: "A dream you dream alone is only a dream. A dream you dream together is reality.",
    author: "John Lennon",
    era: "Musicien, 1940–1980",
    cat: "Inspiration",
    day: 12,
  },
  {
    id: 51,
    text: "Chaque expert a d'abord été un débutant.",
    textEn: "Every expert was once a beginner.",
    author: "Rutherford B. Hayes",
    era: "Homme d'État, 1822–1893",
    cat: "Travail",
    day: 12,
  },
  {
    id: 52,
    text: "Ne regardez jamais en arrière, sauf si c'est pour voir jusqu'où vous avez parcouru.",
    textEn: "Never look back unless you are planning to go that way.",
    author: "Henry David Thoreau",
    era: "Philosophe, 1817–1862",
    cat: "Sagesse",
    day: 12,
  },

  // ── Jour 13 ──
  {
    id: 53,
    text: "La seule chose dont il faut avoir peur, c'est la peur elle-même.",
    textEn: "The only thing we have to fear is fear itself.",
    author: "Franklin D. Roosevelt",
    era: "Président, 1882–1945",
    cat: "Courage",
    day: 13,
  },
  {
    id: 54,
    text: "Vous ne trouverez jamais l'arc-en-ciel si vous regardez vers le bas.",
    textEn: "You'll never find a rainbow if you're looking down.",
    author: "Charlie Chaplin",
    era: "Artiste, 1889–1977",
    cat: "Bonheur",
    day: 13,
  },
  {
    id: 55,
    text: "Tout ce qui brille n'est pas or.",
    textEn: "All that glitters is not gold.",
    author: "William Shakespeare",
    era: "Dramaturge, 1564–1616",
    cat: "Sagesse",
    day: 13,
  },
  {
    id: 56,
    text: "Vous manquez 100 % des tirs que vous ne tentez pas.",
    textEn: "You miss 100% of the shots you don't take.",
    author: "Wayne Gretzky",
    era: "Sportif, né en 1961",
    cat: "Action",
    day: 13,
  },

  // ── Jour 14 ──
  {
    id: 57,
    text: "La grandeur ne consiste pas à être fort, mais à utiliser correctement la force.",
    textEn: "Greatness is not in where we stand, but in what direction we are moving.",
    author: "Oliver Wendell Holmes",
    era: "Juriste, 1841–1935",
    cat: "Sagesse",
    day: 14,
  },
  {
    id: 58,
    text: "Je préfère mourir debout que vivre à genoux.",
    textEn: "I would rather die on my feet than live on my knees.",
    author: "Emiliano Zapata",
    era: "Révolutionnaire, 1879–1919",
    cat: "Courage",
    day: 14,
  },
  {
    id: 59,
    text: "Le talent, c'est ce que vous avez. Le génie, c'est ce qui vous a.",
    textEn: "Talent is what you possess; genius is what possesses you.",
    author: "Malcolm Cowley",
    era: "Critique littéraire, 1898–1989",
    cat: "Créativité",
    day: 14,
  },
  {
    id: 60,
    text: "Connais-toi toi-même.",
    textEn: "Know thyself.",
    author: "Socrate",
    era: "Philosophe, 470–399 av. J.-C.",
    cat: "Philosophie",
    day: 14,
  },

  // ── Jour 15 ──
  {
    id: 61,
    text: "Je t'aime plus que les mots ne peuvent l'exprimer.",
    textEn: "I love you more than words can say.",
    author: "Maëlle Baschou",
    era: "Poétesse, 2007–aujourd'hui",
    cat: "Amour",
    day: 15,
  },
  {
    id: 62,
    text: "Assommé de question, sera t’il le bon pour combler ma passion ?",
    textEn: "Overwhelmed by questions, will he be the one to satisfy my passion ?",
    author: "Maëlle Baschou",
    era: "Poétesse, 2007–aujourd'hui",
    cat: "Amour",
    day: 15,
  },
];

// Biographies courtes des auteurs
const AUTHOR_BIOS = {
  "Albert Einstein": {
    bio: "Physicien théoricien allemand naturalisé américain, Einstein est l'un des plus grands scientifiques de tous les temps. Lauréat du prix Nobel de physique en 1921, il est surtout connu pour sa théorie de la relativité et la formule E=mc². Il était aussi connu pour sa curiosité infinie et sa philosophie de vie humaniste.",
    years: "1879–1955",
  },
  "Mahatma Gandhi": {
    bio: "Leader politique et spirituel indien, Gandhi a guidé l'Inde vers l'indépendance grâce à la résistance non-violente. Sa philosophie de la désobéissance civile a inspiré des mouvements pour les droits civiques à travers le monde entier.",
    years: "1869–1948",
  },
  "Mark Twain": {
    bio: "Samuel Langhorne Clemens, dit Mark Twain, est l'un des plus grands écrivains américains. Auteur de Tom Sawyer et Huckleberry Finn, il est célèbre pour son humour mordant et sa critique sociale déguisée en aventures.",
    years: "1835–1910",
  },
  "Antoine de Saint-Exupéry": {
    bio: "Aviateur et écrivain français, Saint-Exupéry est l'auteur du Petit Prince, l'une des œuvres les plus traduites et lues au monde. Ses écrits mêlent poésie, aventure et méditation sur la condition humaine.",
    years: "1900–1944",
  },
  "Confucius": {
    bio: "Philosophe et enseignant chinois, Confucius est le fondateur du confucianisme. Ses enseignements sur la morale, la famille, la justice et la gouvernance ont profondément influencé les civilisations de l'Asie de l'Est pendant plus de 2 500 ans.",
    years: "551–479 av. J.-C.",
  },
  "Henry Ford": {
    bio: "Industriel américain, fondateur de la Ford Motor Company. Il révolutionna l'industrie automobile en popularisant la chaîne de montage. Sa vision de rendre l'automobile accessible à tous transforma la société du XXe siècle.",
    years: "1863–1947",
  },
  "Sénèque": {
    bio: "Philosophe, dramaturge et homme d'État romain de l'époque impériale. Figure majeure du stoïcisme, ses lettres et essais sur la sagesse, le temps et la mort restent d'une modernité saisissante.",
    years: "4 av. J.-C.–65 ap. J.-C.",
  },
  "Steve Jobs": {
    bio: "Co-fondateur d'Apple, Jobs a révolutionné plusieurs industries : l'informatique personnelle, la musique numérique, le cinéma d'animation et la téléphonie mobile. Visionnaire obsessionnel, il croyait à l'intersection de la technologie et des arts.",
    years: "1955–2011",
  },
  "Nelson Mandela": {
    bio: "Leader anti-apartheid sud-africain, premier président noir de l'Afrique du Sud. Après 27 ans d'emprisonnement, il choisit la réconciliation plutôt que la revanche, devenant un symbole mondial de paix et de justice.",
    years: "1918–2013",
  },
  "Dalaï Lama": {
    bio: "Chef spirituel du bouddhisme tibétain, le 14e Dalaï Lama, Tenzin Gyatso, est lauréat du prix Nobel de la paix en 1989. Ses enseignements sur la compassion, la bienveillance et la paix intérieure touchent des millions de personnes.",
    years: "né en 1935",
  },
  "Eleanor Roosevelt": {
    bio: "Première dame des États-Unis (1933–1945), diplomate et activiste. Elle fut déléguée aux Nations Unies et présida la commission qui rédigea la Déclaration universelle des droits de l'homme.",
    years: "1884–1962",
  },
  "Friedrich Nietzsche": {
    bio: "Philosophe, philologue et poète allemand. Ses œuvres majeures — Ainsi parlait Zarathoustra, Par-delà bien et mal — remettent en question les fondements de la morale et de la religion occidentales.",
    years: "1844–1900",
  },
  "Pablo Picasso": {
    bio: "Peintre, sculpteur et poète espagnol, co-fondateur du cubisme avec Georges Braque. L'une des figures artistiques les plus influentes du XXe siècle, il a produit plus de 20 000 œuvres au cours de sa vie.",
    years: "1881–1973",
  },
  "Lao Tseu": {
    bio: "Philosophe et écrivain chinois, fondateur légendaire du taoïsme. Son œuvre principale, le Tao Te Ching, est l'un des textes les plus traduits au monde et explore l'harmonie, la simplicité et le non-agir.",
    years: "VIe siècle av. J.-C.",
  },
  "Oscar Wilde": {
    bio: "Poète, romancier et dramaturge irlandais, figure flamboyante de l'esthétisme victorien. Auteur du Portrait de Dorian Gray, célèbre pour son esprit acéré et ses aphorismes brillants.",
    years: "1854–1900",
  },
  "Bouddha": {
    bio: "Siddhartha Gautama, le « Bouddha » (l'Éveillé), est le fondateur du bouddhisme. Né dans une famille noble, il abandonna tout pour chercher la vérité, et ses enseignements sur la souffrance et la libération ont transformé des civilisations entières.",
    years: "Ve siècle av. J.-C.",
  },
  "Aristote": {
    bio: "Philosophe grec de l'Antiquité, élève de Platon et précepteur d'Alexandre le Grand. Il a posé les fondements de nombreuses disciplines — logique, biologie, éthique, politique, poétique — et son influence s'étend jusqu'à nos jours.",
    years: "384–322 av. J.-C.",
  },
  "Winston Churchill": {
    bio: "Homme d'État britannique, Premier ministre pendant la Seconde Guerre mondiale. Son leadership inébranlable face au nazisme et ses discours inspirants ont façonné l'histoire du XXe siècle. Lauréat du prix Nobel de littérature en 1953.",
    years: "1874–1965",
  },
  "Paulo Coelho": {
    bio: "Romancier brésilien mondialement connu, auteur de L'Alchimiste, l'un des livres les plus vendus de l'histoire. Son œuvre explore la spiritualité, le destin personnel et la quête de sens.",
    years: "né en 1947",
  },
  "John Lennon": {
    bio: "Musicien, auteur-compositeur et activiste britannique, co-fondateur des Beatles. Après la séparation du groupe, il poursuit une carrière solo et s'engage pour la paix mondiale, jusqu'à son assassinat en 1980.",
    years: "1940–1980",
  },
  "Victor Hugo": {
    bio: "Romancier, poète et dramaturge français, figure de proue du romantisme. Auteur des Misérables et de Notre-Dame de Paris, il fut aussi un homme politique engagé contre la peine de mort et pour les droits des pauvres.",
    years: "1802–1885",
  },
  "Martin Luther King Jr.": {
    bio: "Pasteur baptiste américain et militant des droits civiques. Symbole de la lutte non-violente contre la ségrégation raciale aux États-Unis, son discours « I Have a Dream » reste l'un des plus célèbres de l'histoire. Assassiné en 1968.",
    years: "1929–1968",
  },
  "Socrate": {
    bio: "Philosophe athénien considéré comme l'un des fondateurs de la philosophie occidentale. Il n'a laissé aucun écrit, mais ses idées nous sont parvenues à travers Platon. Il fut condamné à mort pour impiété et a choisi d'accepter la sentence.",
    years: "470–399 av. J.-C.",
  },
  "William Shakespeare": {
    bio: "Dramaturge et poète anglais, Shakespeare est considéré comme le plus grand écrivain de la langue anglaise. Ses 37 pièces de théâtre et 154 sonnets continuent d'être joués et lus dans le monde entier.",
    years: "1564–1616",
  },
  "Thomas Edison": {
    bio: "Inventeur et homme d'affaires américain, surnommé le « Magicien de Menlo Park ». Avec plus de 1 000 brevets à son actif — dont la lampe à incandescence, le phonographe et le cinématographe —, il a transformé la vie quotidienne moderne.",
    years: "1847–1931",
  },
  "Maya Angelou": {
    bio: "Poète, mémorialiste et militante américaine. Son autobiographie Je sais pourquoi chante l'oiseau en cage est une œuvre majeure de la littérature afro-américaine. Elle a reçu de nombreux prix et a lu un poème lors de l'inauguration de Bill Clinton.",
    years: "1928–2014",
  },
  "Galilée": {
    bio: "Astronome, physicien et mathématicien italien, Galilée est l'un des pères de la science moderne. Ses observations au télescope confirmèrent le modèle héliocentrique de Copernic, ce qui lui valut un procès pour hérésie devant l'Inquisition.",
    years: "1564–1642",
  },
  "Jacques Prévert": {
    bio: "Poète et scénariste français, figure emblématique de la culture populaire du XXe siècle. Son recueil Paroles (1946) est l'un des livres de poésie les plus lus en France. Il est aussi connu pour ses scénarios de films comme Les Enfants du paradis.",
    years: "1900–1977",
  },
  "Ambrose Redmoon": {
    bio: "Écrivain et figure contre-culturelle américain, de son vrai nom James Neil Hollingworth. Peu connu du grand public, il est surtout célèbre pour cette seule citation sur le courage, publiée dans le magazine Gnosis en 1991.",
    years: "1933–1996",
  },
  "Dante Alighieri": {
    bio: "Poète florentin du Moyen Âge, auteur de La Divine Comédie, chef-d'œuvre de la littérature mondiale qui décrit un voyage allégorique à travers l'Enfer, le Purgatoire et le Paradis. Il est considéré comme le père de la langue italienne.",
    years: "1265–1321",
  },
  "Thich Nhat Hanh": {
    bio: "Moine bouddhiste zen vietnamien, poète et militant pour la paix. Exilé de son pays pendant 40 ans en raison de ses positions pacifistes durant la guerre du Vietnam, il a popularisé la pleine conscience (mindfulness) en Occident.",
    years: "1926–2022",
  },
  "Eric Hoffer": {
    bio: "Philosophe social et écrivain américain autodidacte. Longtemps docker sur les quais de San Francisco, il publia La Cohue des gueux, une analyse pénétrante des mouvements de masse et du fanatisme, qui lui vaut la Médaille présidentielle de la Liberté.",
    years: "1902–1983",
  },
  "Franklin D. Roosevelt": {
    bio: "32e président des États-Unis, il guida son pays à travers deux crises majeures : la Grande Dépression avec le New Deal et la Seconde Guerre mondiale. Atteint de poliomyélite, il gouverna malgré son handicap et reste l'un des présidents les plus influents de l'histoire américaine.",
    years: "1882–1945",
  },
  "William James": {
    bio: "Philosophe et psychologue américain, fondateur du pragmatisme et de la psychologie fonctionnelle aux États-Unis. Son œuvre Les Principes de psychologie (1890) a posé les bases de la psychologie moderne.",
    years: "1842–1910",
  },
  "C. S. Lewis": {
    bio: "Écrivain et théologien britannique, professeur à Oxford et Cambridge. Auteur des Chroniques de Narnia et des Lettres de l'Oncle Screwtape, il est l'une des figures majeures de la littérature fantastique chrétienne du XXe siècle.",
    years: "1898–1963",
  },
  "Mère Teresa": {
    bio: "Religieuse catholique albanaise-indienne fondatrice des Missionnaires de la Charité à Calcutta. Consacrant sa vie aux plus pauvres parmi les pauvres, elle reçut le prix Nobel de la paix en 1979. Canonisée par le pape François en 2016.",
    years: "1910–1997",
  },
  "Edmund Hillary": {
    bio: "Alpiniste et explorateur néo-zélandais, premier homme à avoir atteint le sommet de l'Everest avec le sherpa Tenzing Norgay, le 29 mai 1953. Il consacra ensuite sa vie à aider les populations sherpa du Népal.",
    years: "1919–2008",
  },
  "Anatole France": {
    bio: "Romancier, journaliste et poète français, lauréat du prix Nobel de littérature en 1921. Connu pour son style élégant et son ironie mordante, il s'engagea activement dans l'affaire Dreyfus aux côtés de Zola.",
    years: "1844–1924",
  },
  "Frank Sinatra": {
    bio: "Chanteur et acteur américain, surnommé « The Voice » et « Ol' Blue Eyes ». Figure emblématique de la musique populaire du XXe siècle, il a vendu plus de 150 millions de disques et reçu un Oscar pour sa performance dans Tant qu'il y aura des hommes.",
    years: "1915–1998",
  },
  "Rutherford B. Hayes": {
    bio: "19e président des États-Unis (1877–1881). Son élection controversée mit fin à la Reconstruction après la guerre de Sécession. Bien que peu cité pour cette phrase dans les sources historiques, son nom y est traditionnellement associé.",
    years: "1822–1893",
  },
  "Henry David Thoreau": {
    bio: "Écrivain, philosophe et naturaliste américain. Son essai La Désobéissance civile et son ouvrage Walden, récit de sa vie en pleine nature, ont profondément influencé la pensée écologiste et les mouvements de résistance non-violente de Gandhi à Martin Luther King.",
    years: "1817–1862",
  },
  "Charlie Chaplin": {
    bio: "Acteur, réalisateur et compositeur britannique, génie du cinéma muet. Son personnage de Charlot, petit vagabond plein de poésie, le rendit célèbre dans le monde entier. Son film Le Dictateur (1940) est une satire courageuse du nazisme.",
    years: "1889–1977",
  },
  "Wayne Gretzky": {
    bio: "Hockeyeur canadien surnommé « The Great One », considéré comme le meilleur joueur de hockey sur glace de tous les temps. Il détient encore aujourd'hui la plupart des records de la LNH, dont celui des points en carrière.",
    years: "né en 1961",
  },
  "Oliver Wendell Holmes": {
    bio: "Juriste américain, juge à la Cour suprême pendant 30 ans. Surnommé « The Great Dissenter » pour ses opinions dissidentes influentes, il fut l'un des fondateurs du mouvement juridique du réalisme et défenseur de la liberté d'expression.",
    years: "1841–1935",
  },
  "Emiliano Zapata": {
    bio: "Révolutionnaire mexicain et figure centrale de la Révolution mexicaine (1910–1920). Chef du mouvement paysan, il se battit pour la réforme agraire et la restitution des terres aux communautés indigènes. Il reste un symbole de la lutte pour la justice sociale en Amérique latine.",
    years: "1879–1919",
  },
  "Malcolm Cowley": {
    bio: "Critique littéraire, éditeur et écrivain américain. Il est surtout connu pour avoir contribué à la reconnaissance de la Génération Perdue (Hemingway, Fitzgerald) et pour son œuvre autobiographique Exil's Return sur les expatriés américains à Paris dans les années 1920.",
    years: "1898–1989",
  },
  "George Bernard Shaw": {
    bio: "Dramaturge, critique et polémiste irlandais, l'une des figures majeures du théâtre occidental. Lauréat du prix Nobel de littérature en 1925, il est connu pour ses pièces à la fois brillantes et engagées, dont Pygmalion, adaptée plus tard en comédie musicale (My Fair Lady).",
    years: "1856–1950",
  },
  "Saint Augustin": {
    bio: "Théologien et philosophe de l'Antiquité tardive, évêque d'Hippone (aujourd'hui Annaba, Algérie). Ses Confessions et La Cité de Dieu comptent parmi les œuvres les plus influentes de la pensée occidentale, posant les bases de la théologie chrétienne médiévale.",
    years: "354–430",
  },
  "Jimi Hendrix": {
    bio: "Guitariste, chanteur et compositeur américain, considéré comme l'un des plus grands guitaristes de l'histoire du rock. En seulement quatre ans de carrière, il a révolutionné la façon de jouer de la guitare électrique et laissé une empreinte indélébile sur la musique populaire.",
    years: "1942–1970",
  },
  "Maëlle Baschou": {
    bio: "Maëlle Baschou est une jeune femme dont les mots traduisent avec sincérité ce que le cœur ressent. Ses citations, empreintes de tendresse et d'authenticité, rappellent que les plus belles pensées naissent souvent des émotions les plus simples.",
    years: "2007 — aujourd'hui",
  },
};

// Nombre de jours différents dans le jeu de données
const TOTAL_DAYS = Math.max(...ALL_QUOTES.map(q => q.day)) + 1;
